
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umwawpkcurgvnndmcyvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtd2F3cGtjdXJndm5uZG1jeXZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwNDU5NjgsImV4cCI6MjA1MzYyMTk2OH0.2eyDL0e2UrnSE9ykJW215G5Af5sTw5MI9pFkXJRtXAY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true
  }
});
